// Generated by scripts/generate-case-site-data.mjs. Do not edit by hand.

export const caseMetadata = {
  "beauty-d2c-voc": {
    "title": {
      "ko": "Beauty/D2C 글로벌 VOC → 업무 제안",
      "en": "Beauty/D2C global VOC → workflow proposal"
    },
    "industry": "consumer-retail",
    "difficulty": 1,
    "risk": "moderate",
    "evidenceStage": "public-simulation",
    "readiness": [
      "low",
      "saas"
    ],
    "recommendedAfter": [],
    "learningOrder": 2,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A1-A2",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [
      1
    ],
    "designedProjectStages": [
      1,
      2,
      3,
      5
    ]
  },
  "care-conversation-record": {
    "title": {
      "ko": "상담·진료 대화에서 검토 가능한 기록과 위험 이관까지",
      "en": "From care conversations to reviewed records and risk escalation"
    },
    "industry": "healthcare-social-care",
    "difficulty": 5,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "low",
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "centralized-mail-assist",
      "public-service-petition-response"
    ],
    "learningOrder": 14,
    "currentWriteImpact": "none",
    "designedWriteImpact": "draft-only",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A2",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3
    ]
  },
  "centralized-mail-assist": {
    "title": {
      "ko": "중앙 메일 업무 보조 통합",
      "en": "Centralized Mail Assistance Integration"
    },
    "industry": "cross-industry",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "slack-meeting-actions"
    ],
    "learningOrder": 8,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4,
      5
    ]
  },
  "company-agent-operating-layer": {
    "title": {
      "ko": "회사 에이전트 운영 계층",
      "en": "Company Agent Operating Layer"
    },
    "industry": "cross-industry",
    "difficulty": 5,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "slack-meeting-actions",
      "centralized-mail-assist"
    ],
    "learningOrder": 15,
    "currentWriteImpact": "none",
    "designedWriteImpact": "mixed",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      2,
      3,
      4,
      5
    ]
  },
  "corporate-card-expense": {
    "title": {
      "ko": "법인카드·경비 증빙에서 승인 가능한 전표 초안까지",
      "en": "From corporate-card evidence to an approvable journal-entry draft"
    },
    "industry": "cross-industry",
    "difficulty": 2,
    "risk": "moderate",
    "evidenceStage": "simulation-design",
    "readiness": [
      "low",
      "saas"
    ],
    "recommendedAfter": [
      "file-csv-to-ax-hub"
    ],
    "learningOrder": 5,
    "currentWriteImpact": "none",
    "designedWriteImpact": "draft-only",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A2",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3
    ]
  },
  "credit-underwriting-review": {
    "title": {
      "ko": "기업 자료에서 여신·인수심사 검토 초안까지",
      "en": "From company evidence to a credit and underwriting review draft"
    },
    "industry": "financial-services",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "low",
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "corporate-card-expense",
      "vendor-master-account-change"
    ],
    "learningOrder": 11,
    "currentWriteImpact": "none",
    "designedWriteImpact": "draft-only",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A2",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3
    ]
  },
  "electronic-tax-invoice-reconciliation": {
    "title": {
      "ko": "매출 근거에서 전자세금계산서 발행·입금 대사까지",
      "en": "From sales evidence to electronic tax invoice and payment reconciliation"
    },
    "industry": "cross-industry",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "corporate-card-expense"
    ],
    "learningOrder": 9,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4
    ]
  },
  "employee-lifecycle-access": {
    "title": {
      "ko": "입사·이동·퇴사에 맞춘 계정·권한 운영",
      "en": "Employee lifecycle account and access operations"
    },
    "industry": "cross-industry",
    "difficulty": 3,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "slack-meeting-actions"
    ],
    "learningOrder": 7,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4,
      5
    ]
  },
  "equipment-anomaly-maintenance": {
    "title": {
      "ko": "설비 이상 신호에서 검토 가능한 정비 제안까지",
      "en": "From equipment anomaly signals to a reviewable maintenance proposal"
    },
    "industry": "manufacturing",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "it"
    ],
    "recommendedAfter": [
      "inventory-exception-replenishment"
    ],
    "learningOrder": 13,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4
    ]
  },
  "file-csv-to-ax-hub": {
    "title": {
      "ko": "흩어진 파일·CSV를 검토 가능한 업무 허브(AX Hub)로",
      "en": "From Scattered Files and CSVs to a Reviewable AX Hub"
    },
    "industry": "cross-industry",
    "difficulty": 1,
    "risk": "moderate",
    "evidenceStage": "simulation-design",
    "readiness": [
      "low",
      "saas"
    ],
    "recommendedAfter": [],
    "learningOrder": 1,
    "currentWriteImpact": "none",
    "designedWriteImpact": "draft-only",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A2",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      5
    ]
  },
  "inventory-exception-replenishment": {
    "title": {
      "ko": "재고 예외에서 발주·창고 이동 제안까지",
      "en": "From inventory exceptions to purchase and transfer proposals"
    },
    "industry": "consumer-retail",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "slack-meeting-actions",
      "vendor-master-account-change"
    ],
    "learningOrder": 12,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4
    ]
  },
  "public-service-petition-response": {
    "title": {
      "ko": "공공 민원에서 근거가 표시된 답변 초안과 중복 민원 묶음까지",
      "en": "From public petitions to cited response drafts and reviewable clusters"
    },
    "industry": "public-sector",
    "difficulty": 2,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "low",
      "saas"
    ],
    "recommendedAfter": [
      "beauty-d2c-voc"
    ],
    "learningOrder": 3,
    "currentWriteImpact": "none",
    "designedWriteImpact": "draft-only",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A2",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3
    ]
  },
  "regulated-evidence-document": {
    "title": {
      "ko": "근거 자료에서 출처가 연결된 규제 문서 초안까지",
      "en": "From evidence packets to a source-linked regulated document draft"
    },
    "industry": "legal-life-sciences",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "low",
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "file-csv-to-ax-hub",
      "corporate-card-expense"
    ],
    "learningOrder": 6,
    "currentWriteImpact": "none",
    "designedWriteImpact": "draft-only",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A2",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3
    ]
  },
  "slack-meeting-actions": {
    "title": {
      "ko": "회의 전후 Slack 신호를 승인 가능한 실행 항목으로",
      "en": "From Slack Meeting Signals to Human-Approved Actions"
    },
    "industry": "cross-industry",
    "difficulty": 2,
    "risk": "moderate",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "file-csv-to-ax-hub"
    ],
    "learningOrder": 4,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4,
      5
    ]
  },
  "vendor-master-account-change": {
    "title": {
      "ko": "거래처 등록·계좌 변경을 검증 가능한 승인 흐름으로",
      "en": "Vendor onboarding and bank-account change with verifiable approval"
    },
    "industry": "cross-industry",
    "difficulty": 4,
    "risk": "high",
    "evidenceStage": "simulation-design",
    "readiness": [
      "saas",
      "it"
    ],
    "recommendedAfter": [
      "corporate-card-expense"
    ],
    "learningOrder": 10,
    "currentWriteImpact": "none",
    "designedWriteImpact": "approved-sandbox-write",
    "currentAutonomy": "A0",
    "designedAutonomy": "A1-A3",
    "implementedProjectStages": [],
    "designedProjectStages": [
      1,
      2,
      3,
      4
    ]
  }
} as const;

export const generatedCaseCounts = {
  "total": 15,
  "publicSimulation": 1,
  "simulationDesign": 14
} as const;
