export type Language = "ko" | "en";
export type Role = "all" | "practitioner" | "builder" | "leader" | "guardian";
export type Readiness = "all" | "it" | "saas" | "low";

type LocalizedText = { ko: string; en: string };

export type RoadmapNode = {
  id: string;
  title: LocalizedText;
  description: LocalizedText;
  evidence: LocalizedText;
  doc: string;
  roles: Exclude<Role, "all">[];
  readiness: Exclude<Readiness, "all">[];
};

export type RoadmapGroup = {
  id: string;
  label: LocalizedText;
  prompt: LocalizedText;
  nodes: RoadmapNode[];
};

const everyRole: Exclude<Role, "all">[] = [
  "practitioner",
  "builder",
  "leader",
  "guardian",
];
const everyReadiness: Exclude<Readiness, "all">[] = ["it", "saas", "low"];

function node(
  id: string,
  koTitle: string,
  enTitle: string,
  koDescription: string,
  enDescription: string,
  koEvidence: string,
  enEvidence: string,
  doc: string,
  roles = everyRole,
  readiness = everyReadiness,
): RoadmapNode {
  return {
    id,
    title: { ko: koTitle, en: enTitle },
    description: { ko: koDescription, en: enDescription },
    evidence: { ko: koEvidence, en: enEvidence },
    doc,
    roles,
    readiness,
  };
}

export const roadmapGroups: RoadmapGroup[] = [
  {
    id: "start",
    label: { ko: "시작점", en: "Starting point" },
    prompt: {
      ko: "직함보다 이번 업무에서 내가 내릴 결정과 맡을 책임, 준비 상태를 먼저 확인한다.",
      en: "Begin with the decisions you own and the workflow's readiness, not your title.",
    },
    nodes: [
      node(
        "persona",
        "역할 선택",
        "Persona selection",
        "업무 정의, 구현, 투자, 통제 중에서 자신이 맡을 책임을 확인한다.",
        "Identify your responsibility for workflow definition, implementation, investment, or control.",
        "역할별 결정권과 대체 책임자",
        "Decision rights and backup owners",
        "start-here/persona-selector.md",
      ),
      node(
        "readiness",
        "조직 준비도",
        "Organization readiness",
        "업무, 데이터, 시스템, 권한, 운영, 현업 적용이 얼마나 준비됐는지 보고 첫 실행 범위를 정한다.",
        "Bound the first action by workflow, data, systems, permissions, operations, and adoption.",
        "준비 항목별 확인 결과",
        "Confirmed, partial, and unknown diagnosis",
        "start-here/organization-readiness.md",
      ),
      node(
        "glossary",
        "비개발자 용어 안내",
        "Non-developer glossary",
        "LLM, RAG, 에이전트(Agent), MCP, 평가, 로그가 업무에서 맡는 역할과 위험을 이해한다.",
        "Understand LLMs, RAG, agents, MCP, evaluation, and logs as workflow decisions and risks.",
        "기술 경계와 협업 질문",
        "Technical boundaries and collaboration questions",
        "start-here/non-developer-glossary.md",
        ["practitioner", "leader", "guardian"],
        ["saas", "low"],
      ),
    ],
  },
  {
    id: "roles",
    label: { ko: "역량과 협업 역할", en: "Competencies and collaboration" },
    prompt: {
      ko: "AX 엔지니어가 맡을 일과 현업, 리더, 데이터, 보안, 운영 담당자가 함께 결정할 일을 나눈다.",
      en: "Separate the AX Engineer's responsibility from the decisions owned by business, leadership, data, security, and operations partners.",
    },
    nodes: [
      node(
        "competency",
        "8개 역량 지도",
        "Eight-area competency map",
        "사업성 판단, 업무, 데이터, 통합, AI, 운영, 현업 정착, 조직 학습에서 부족한 부분을 찾는다.",
        "Find gaps across business, workflow, data, integration, AI, operations, adoption, and learning.",
        "영역별 결과물과 실패 대응 기준",
        "Deliverables and failure handling by area",
        "roadmap/competency-map.md",
      ),
      node(
        "business-track",
        "현업 실무자 협업 안내",
        "Business partner guide",
        "현재 업무와 목표 업무 흐름, 검수, 예외, SOP, 현업 정착, 기존 절차의 종료 기준을 정한다.",
        "Define current and target flows, acceptance, exceptions, SOP, adoption, and retirement criteria.",
        "업무 흐름·검수·UAT·SOP",
        "Flow, rubric, UAT, and SOP",
        "tracks/business-practitioner.md",
        ["practitioner"],
      ),
      node(
        "builder-track",
        "AX 엔지니어 실행 경로",
        "AX Engineer path",
        "소프트웨어와 AI를 기존 시스템에 통합하고, 평가부터 배포와 복구까지 한 흐름으로 운영한다.",
        "Connect software, AI, integration, evaluation, deployment, and recovery into an operable workflow system.",
        "코드·실행 규칙·평가·운영 기록",
        "Code, execution rules, evaluation, and operating records",
        "tracks/ax-builder.md",
        ["builder"],
      ),
      node(
        "leader-track",
        "리더·의사결정자 협업 안내",
        "Leader and decision-owner guide",
        "업무 포트폴리오, 투자, 책임, 조달을 관리하고 외부 공급자를 교체하거나 계약을 종료할 기준과 확장 기준을 정한다.",
        "Operate portfolio, investment, accountability, procurement, vendor exit, and scale.",
        "결정 이력·책임표·중단 기준",
        "Decision history, ownership matrix, and stop criteria",
        "tracks/leader-and-governance.md",
        ["leader"],
      ),
      node(
        "guardian-track",
        "데이터·보안·운영 협업 안내",
        "Data, security, and operations guide",
        "데이터의 수집·사용·보관·삭제, 접근 권한, 운영 상태 확인, 장애 대응, 감사 방식을 처음부터 함께 설계한다.",
        "Co-design data lifecycle, access, observability, incidents, and audit from the start.",
        "데이터 지도·권한표·위협 모델·복구",
        "Data map, permissions, threat model, and recovery",
        "tracks/data-security-operations.md",
        ["guardian"],
      ),
    ],
  },
  {
    id: "technical",
    label: { ko: "기술 역량", en: "Technical capabilities" },
    prompt: {
      ko: "에이전트부터 도입하지 않는다. 성공 기준을 충족하는 가장 단순한 구조를 먼저 고른다.",
      en: "Choose the simplest design that meets the success criteria before adding agent complexity.",
    },
    nodes: [
      node(
        "software-api",
        "소프트웨어와 API",
        "Software and APIs",
        "상태와 권한을 보존하고, 중복 실행과 일부 실패를 처리하면서 기존 시스템을 연결한다.",
        "Connect source systems while preserving state, permissions, duplicates, and partial failure.",
        "API·상태·오류 계약과 테스트",
        "API, state, error contracts, and tests",
        "technical-foundations/software-and-api.md",
        ["builder", "guardian"],
        ["it", "saas"],
      ),
      node(
        "llm",
        "LLM 기초",
        "LLM foundations",
        "토큰, 컨텍스트, 검색, 구조화 출력, 비용과 모델 변경 위험을 다룬다.",
        "Handle tokens, context, retrieval, structured output, cost, and model-change risk.",
        "기준선·평가·비용·버전 비교",
        "Baseline, evaluation, cost, and version comparison",
        "technical-foundations/llm-foundations.md",
        ["practitioner", "builder", "guardian"],
      ),
      node(
        "agent",
        "에이전트 시스템",
        "Agent systems",
        "Agent Loop가 필요한 조건을 확인하고 상태, 중단, 메모리, 담당자 인계 기준을 정한다.",
        "Justify Agent Loops and define state, stopping, memory, and human handoff.",
        "단순 대안 비교와 실패 주입",
        "Simpler-alternative comparison and failure injection",
        "technical-foundations/agent-systems.md",
        ["builder", "guardian"],
        ["it", "saas"],
      ),
      node(
        "tools-mcp",
        "도구 호출과 MCP",
        "Tool calling and MCP",
        "모델의 제안을 곧바로 실행하지 않고, 그 사이에 스키마, 정책, 권한, 승인 절차를 둔다.",
        "Place schema, policy, permission, and approval between model output and action.",
        "도구 카탈로그·권한·실행 로그",
        "Tool catalog, permissions, and action logs",
        "technical-foundations/tools-and-mcp.md",
        ["builder", "guardian"],
        ["it", "saas"],
      ),
      node(
        "evaluation",
        "평가와 테스트",
        "Evaluation and testing",
        "정상·경계·실패·공격 사례로 검색, 생성, 도구, 업무 결과를 나눠 판정한다.",
        "Judge retrieval, generation, tools, and outcomes with normal, edge, failure, and attack cases.",
        "평가 세트·판정 기준·회귀 결과",
        "Evaluation set, rubric, and regression results",
        "technical-foundations/evaluation-and-testing.md",
      ),
      node(
        "operations",
        "운영과 관측성",
        "Operations and observability",
        "품질·비용·지연·승인 상태·장애를 추적하고 필요하면 중단·복구하거나 수동 절차로 돌린다.",
        "Trace quality, cost, latency, approval, and incidents and support stop and recovery.",
        "SLO·경보·복구 훈련·인수인계",
        "SLO, alerts, recovery drill, and handoff",
        "technical-foundations/production-operations.md",
        ["builder", "leader", "guardian"],
        ["it", "saas"],
      ),
      node(
        "security",
        "보안과 개인정보",
        "Security and privacy",
        "처리 목적, 최소 권한, 프롬프트 공격, 데이터 보유와 사고 대응을 설계한다.",
        "Design purpose, least privilege, prompt-attack defense, retention, and incident response.",
        "데이터 흐름·위협 모델·보안 시험",
        "Data flow, threat model, and security tests",
        "technical-foundations/security-and-privacy.md",
      ),
    ],
  },
  {
    id: "lifecycle",
    label: { ko: "AX 업무 전환 8단계", en: "Eight-stage transformation" },
    prompt: {
      ko: "순서대로 진행하되, 운영 결과나 새로운 제약이 나오면 앞 단계로 돌아가 다시 확인한다.",
      en: "Proceed in order, returning to earlier stages when operating results or new constraints require it.",
    },
    nodes: [
      node("stage-1", "목표와 경계", "Goals and boundaries", "무엇을 바꾸고 AI에 맡기지 않을 일을 정한다.", "Define what changes and what AI must not do.", "기준선·제외할 목표·중단 조건", "Baseline, non-goals, and stop conditions", "delivery-lifecycle/01-outcomes-and-boundaries.md"),
      node("stage-2", "현재 업무 파악", "Understand the current workflow", "실제 흐름, 대기, 예외와 인수인계를 확인한다.", "Observe actual flow, waiting, exceptions, and handoffs.", "현재 흐름·예외·병목", "Current flow, exceptions, and bottlenecks", "delivery-lifecycle/02-workflow-discovery.md"),
      node("stage-3", "업무 흐름 재설계", "Redesign the workflow", "제거·통합·표준화·보조·승인·자동 실행을 구분한다.", "Separate removal, standardization, assistance, approval, and action.", "목표 흐름·책임 배분", "Target flow and responsibility", "delivery-lifecycle/03-process-redesign.md"),
      node("stage-4", "데이터와 업무 맥락", "Data and context", "최신 상태를 확인할 원본, 출처, 용어, 누락과 소유자를 정한다.", "Define authoritative systems, provenance, terms, missingness, and owners.", "데이터 계약·용어집·계보", "Data contract, glossary, and lineage", "delivery-lifecycle/04-data-and-context.md"),
      node("stage-5", "실행 규칙과 통제", "Execution rules and controls", "입력·출력·평가·권한·승인·기록·복구 규칙을 정한다.", "Define rules for input, output, evaluation, permission, approval, records, and recovery.", "업무 실행 규칙·승인표·위협 모델", "Execution rules, approval matrix, and threat model", "delivery-lifecycle/05-execution-contracts.md"),
      node("stage-6", "배포와 운영", "Production deployment", "작은 범위로 배포한 뒤 상태를 살피고, 장애가 나면 롤백하거나 수동 절차로 돌린다.", "Operate bounded deployment, observability, incidents, rollback, and fallback.", "배포·SLO·복구 기록", "Deployment, SLO, and recovery records", "delivery-lifecycle/06-production-deployment.md", everyRole, ["it", "saas"]),
      node("stage-7", "현업 적용과 역할 전환", "Workflow transition and role change", "사용자 검수, SOP, 지원, 이중 운영과 기존 절차 종료를 다룬다.", "Handle UAT, SOP, support, parallel operation, and retirement.", "UAT·SOP·현업 정착·종료 결정", "UAT, SOP, adoption, and retirement decision", "delivery-lifecycle/07-adoption-and-change.md"),
      node("stage-8", "표준화와 확장", "Standardization and scale", "두 번째 업무에서도 검증된 실행 규칙만 공통 기반에 포함할 후보로 삼는다.", "Promote only contracts validated in a second workflow.", "재사용 비교표·버전·폐기 기준", "Reuse comparison, version, and retirement policy", "delivery-lifecycle/08-standardization-and-scale.md"),
    ],
  },
  {
    id: "projects",
    label: { ko: "실습 프로젝트", en: "Practice projects" },
    prompt: {
      ko: "기능 수를 늘리기보다 외부 시스템과 실제 업무에 미치는 영향, 배포 책임을 한 단계씩 키운다.",
      en: "Increase external impact and delivery responsibility one step at a time.",
    },
    nodes: [
      node("project-1", "안전한 보조 도구", "Safe assistant", "공개·합성 데이터로 출처 표시, 거절, 평가가 제대로 작동하는지 검증한다.", "Validate provenance, refusal, and evaluation with public or synthetic data.", "20개 이상의 평가 사례와 별도 검토 결과", "At least 20 eval cases and independent judgment", "projects/01-safe-assistant.md"),
      node("project-2", "담당자 승인 워크플로우", "Human-approved workflow", "담당자가 근거와 변경 전후를 보고 승인하거나 수정 또는 거절한다.", "Approve, edit, or reject after reviewing evidence and before-and-after state.", "승인 기준·우회 시험·수정 부담", "Approval rubric, bypass tests, and correction burden", "projects/02-human-approved-workflow.md"),
      node("project-3", "샌드박스 통합", "Sandbox integration", "테스트 시스템에서 권한, 중복, 부분 실패와 복구를 시험한다.", "Test permissions, duplicates, partial failure, and recovery in test systems.", "격리·중복 방지·복구 훈련", "Isolation, deduplication, and recovery drill", "projects/03-sandbox-integration.md", ["builder", "guardian"], ["it", "saas"]),
      node("project-4", "운영 파일럿", "Production pilot", "사용자와 범위를 제한해 위험이 낮은 업무 하나를 실제로 운영한다.", "Operate one low-risk workflow with bounded users and scope.", "SLO·UAT·장애·인수인계", "SLO, UAT, incidents, and handoff", "projects/04-production-pilot.md", everyRole, ["it", "saas"]),
      node("project-5", "두 번째 업무 재사용", "Second-workflow reuse", "실제로 재사용한 실행 규칙과 업무마다 새로 추가한 항목을 구분한다.", "Separate execution rules actually reused from workflow-specific additions.", "업무 비교·추가 구현 비용·공통화 여부", "Workflow comparison, addition cost, and standardization decision", "projects/05-second-workflow-reuse.md", ["builder", "leader", "guardian"]),
    ],
  },
  {
    id: "cases",
    label: { ko: "현업 조합 사례", en: "Applied AX cases" },
    prompt: {
      ko: "데이터, 도구, 승인, 운영 조건을 실제 업무 맥락에 조합하는 방식을 사례별로 살핀다.",
      en: "Explore how data, tools, approval, and operating controls combine in applied workflow contexts.",
    },
    nodes: [
      node(
        "case-beauty-d2c-voc",
        "Beauty/D2C 글로벌 VOC → 업무 제안",
        "Beauty/D2C global VOC → workflow proposal",
        "공개 VOC의 원문과 출처를 보존하고, 사람이 근거를 확인한 뒤 업무 제안을 승인하는 흐름을 연습한다.",
        "Practice preserving public VOC and its provenance before a person reviews evidence and approves work proposals.",
        "공개 데이터 기반 학습 시뮬레이션·평가 기준",
        "Public-data learning simulation and evaluation criteria",
        "case-studies/beauty-d2c-voc/README.md",
        everyRole,
        ["low", "saas"],
      ),
      node(
        "case-electronic-tax-invoice-reconciliation",
        "매출 근거에서 전자세금계산서 발행·입금 대사까지",
        "From sales evidence to electronic tax invoice and payment reconciliation",
        "계약·주문·검수와 회계 상태를 확인하고, 담당자 승인 뒤 테스트 발행 결과와 입금을 다시 맞추는 흐름을 설계한다.",
        "Design a flow that checks transaction and accounting evidence, obtains accountable approval, and reconciles sandbox issuance and payment results.",
        "시뮬레이션 설계·거래 근거·승인·중복 방지·대사 기준",
        "Simulation design, transaction evidence, approval, deduplication, and reconciliation criteria",
        "case-studies/electronic-tax-invoice-reconciliation/README.md",
        ["practitioner", "builder", "guardian"],
        ["it", "saas"],
      ),
      node(
        "case-file-csv-to-ax-hub",
        "흩어진 파일·CSV를 검토 가능한 AX Hub로",
        "From Scattered Files and CSVs to a Reviewable AX Hub",
        "개인 AI 산출물과 분산 CSV를 구조화된 Hub로 모으고, 사람이 검토할 Slack 요약 초안을 만드는 흐름을 설계한다.",
        "Design a flow that consolidates personal AI outputs and distributed CSV files into a structured hub, then drafts a human-reviewed Slack digest.",
        "학습용 시뮬레이션 설계·데이터 계약·검토 기준",
        "Learning-simulation design, data contract, and review criteria",
        "case-studies/file-csv-to-ax-hub/README.md",
        ["practitioner", "builder", "guardian"],
        ["saas", "low"],
      ),
      node(
        "case-slack-meeting-actions",
        "회의 전후 Slack 신호를 승인 가능한 실행 항목으로",
        "From Slack Meeting Signals to Human-Approved Actions",
        "Slack, Notion, Google Workspace, monday.com을 연결해 사람 승인 뒤 샌드박스 업무를 만드는 흐름을 설계한다.",
        "Design a flow across Slack, Notion, Google Workspace, and monday.com that creates sandbox tasks only after human approval.",
        "학습용 시뮬레이션 설계·승인·후속 확인 기준",
        "Learning-simulation design, approval, and follow-up criteria",
        "case-studies/slack-meeting-actions/README.md",
        ["practitioner", "builder", "guardian"],
        ["it", "saas"],
      ),
      node(
        "case-employee-lifecycle-access",
        "입사·이동·퇴사에 맞춘 계정·권한 운영",
        "Employee lifecycle account and access operations",
        "직원 상태를 기준으로 필요한 계정·권한·장비 작업을 준비하고, 역할별 승인 뒤 샌드박스에 반영·회수하는 흐름을 설계한다.",
        "Design lifecycle-driven account, access, and device work with role-based approval, sandbox action, and revocation.",
        "시뮬레이션 설계·최소 권한·역할별 승인·부분 실패 복구",
        "Simulation design, least privilege, role-based approval, and partial-failure recovery",
        "case-studies/employee-lifecycle-access/README.md",
        everyRole,
        ["it", "saas"],
      ),
      node(
        "case-corporate-card-expense",
        "법인카드·경비 증빙에서 승인 가능한 전표 초안까지",
        "From corporate-card evidence to an approvable journal-entry draft",
        "합성 카드 거래와 영수증을 연결하고, 누락·중복·정책 예외를 검토한 뒤 회계 샌드박스용 전표 초안을 만든다.",
        "Match synthetic card transactions and receipts, review missing evidence, duplicates, and policy exceptions, then prepare an accounting-sandbox draft.",
        "시뮬레이션 설계·문서 추출·정책 예외·전표 초안 기준",
        "Simulation design, document extraction, policy exceptions, and journal-entry draft criteria",
        "case-studies/corporate-card-expense/README.md",
        ["practitioner", "builder", "guardian"],
        ["low", "saas"],
      ),
      node(
        "case-vendor-master-account-change",
        "거래처 등록·계좌 변경을 검증 가능한 승인 흐름으로",
        "Vendor onboarding and bank-account change with verifiable approval",
        "거래처 서류와 기존 마스터를 대조하고, 계좌 변경을 독립적으로 재확인한 뒤 이중 승인된 변경만 샌드박스에 반영한다.",
        "Compare vendor evidence with master data, independently reconfirm account changes, and write only dual-approved changes to a sandbox.",
        "시뮬레이션 설계·마스터 데이터·역할 분리·실제 상태 대조",
        "Simulation design, master data, separation of duties, and actual-state reconciliation",
        "case-studies/vendor-master-account-change/README.md",
        everyRole,
        ["it", "saas"],
      ),
      node(
        "case-inventory-exception-replenishment",
        "재고 예외에서 발주·창고 이동 제안까지",
        "From inventory exceptions to purchase and transfer proposals",
        "재고·주문·입고·이동 상태를 다시 확인하고, 담당자가 승인할 발주·창고 이동·보류 후보를 비교한다.",
        "Reread inventory, order, inbound, and transfer state, then compare purchase, transfer, and hold options for accountable approval.",
        "시뮬레이션 설계·상태 재조회·중복 방지·부분 실패 복구",
        "Simulation design, state refresh, deduplication, and partial-failure recovery",
        "case-studies/inventory-exception-replenishment/README.md",
        everyRole,
        ["it", "saas"],
      ),
      node(
        "case-centralized-mail-assist",
        "중앙 메일 업무 보조 통합",
        "Centralized Mail Assistance Integration",
        "선택한 메일만 중앙에서 읽고 분류·초안을 제안하며, 외부 발송은 사람 승인 뒤에만 허용하도록 설계한다.",
        "Design centralized reading, classification, and drafting for opted-in mail, while allowing outbound delivery only after human approval.",
        "고위험 학습 시뮬레이션 설계·권한 경계·승인 기준",
        "High-risk learning-simulation design, permission boundaries, and approval criteria",
        "case-studies/centralized-mail-assist/README.md",
        ["practitioner", "builder", "guardian"],
        ["it", "saas"],
      ),
      node(
        "case-company-agent-operating-layer",
        "회사 에이전트 운영 계층",
        "Company Agent Operating Layer",
        "두 번째 업무 재사용 결과를 기준으로 공통화 범위를 정하고, 업무별 신뢰 경계와 실행 책임을 분리하도록 캡스톤을 설계한다.",
        "Design a capstone that uses second-workflow reuse results to decide what to share while separating trust boundaries and execution responsibility by workflow.",
        "조직 확장용 참조 캡스톤 설계·재사용·운영 기준",
        "Organizational-scale reference capstone design, reuse, and operating criteria",
        "case-studies/company-agent-operating-layer/README.md",
        ["builder", "leader", "guardian"],
        ["it", "saas"],
      ),
    ],
  },
  {
    id: "scale",
    label: { ko: "운영과 조직 학습", en: "Operations and organizational learning" },
    prompt: {
      ko: "AI가 참여하는 새 업무를 조직이 안전하게 추가하고 개선하며 중단할 수 있게 한다.",
      en: "Leave the capability to add, improve, and stop workflows safely.",
    },
    nodes: [
      node("maturity", "조직 AX 성숙도", "Organization AX maturity", "개인 실험부터 공통 운영 기반과 현업 자립까지의 상태를 단계별로 진단한다.", "Assess repeatable capability from individual experiments to shared operations.", "M0~M4 항목별 운영 상태", "M0–M4 operating state by dimension", "organization-maturity/README.md"),
      node("practice", "12주 실습 경로", "12-week practice path", "한 업무의 발견·배포 뒤 두 번째 업무에서 재사용을 검증한다.", "Discover and deploy one workflow, then test reuse in a second.", "주차별 결정·실패·산출물", "Weekly decisions, failures, and artifacts", "learning-paths/12-week-practice.md"),
      node("toolkit", "실무 템플릿", "Shared toolkit", "업무 발굴, 평가, 실행 규칙, 실험, 근거 기록 템플릿을 재사용한다.", "Reuse workflow discovery, evaluation, execution-rule, experiment, and evidence templates.", "다른 사람이 이어서 사용할 문서", "Working documents another person can continue", "toolkit/README.md"),
    ],
  },
];

export const roleLabels: Record<Role, LocalizedText> = {
  all: { ko: "모든 역할", en: "All roles" },
  practitioner: { ko: "현업 실무자", en: "Business partner" },
  builder: { ko: "AX 엔지니어", en: "AX Engineer" },
  leader: { ko: "리더·의사결정자", en: "Leader and decision owner" },
  guardian: { ko: "데이터·보안·운영 담당자", en: "Data, security, operations" },
};

export const readinessLabels: Record<Readiness, LocalizedText> = {
  all: { ko: "모든 준비 상태", en: "All readiness states" },
  it: { ko: "사내 시스템·API 보유", en: "IT-native" },
  saas: { ko: "SaaS 중심", en: "SaaS-centered" },
  low: { ko: "메신저·파일 중심", en: "File-and-message centered" },
};
